language: ruby
script: make test
rvm:
  - 2.3.1
  - 2.2.5
  - ruby-head
env:
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
